name: jupyterlab_pyspark
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - pyspark
  - findspark
  - openjdk
  - ipywidgets
  - jupyterlab
  - nodejs
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
